name: denguego
description: A new Flutter application.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  firebase_auth: ^1.0.0
  cloud_firestore: ^1.0.0
  firebase_core: ^1.0.0
  provider: ^5.0.0
  flutter_spinkit: ^5.0.0
  google_maps_flutter: ^2.0.1
  http: ^0.13.0
  html: ^0.15.0
  web_scraper: ^0.1.4
  json_serializable: ^4.1.0
  video_player: ^2.0.2
  chewie: ^1.0.0
  flushbar: ^1.10.4
  dcdg: ^3.0.0
  dropdownfield: ^1.0.3
  custom_searchable_dropdown: ^1.0.5
  location: ^2.3.5
  geocoding: ^2.0.0
  geolocator: ^7.0.1
  email_validator: ^2.0.1
  email_auth: ^0.0.1+3
  permission_handler: ^3.0.0
  location_permissions: ^3.0.0

  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  flutter_local_notifications: ^5.0.0+1
  rxdart: ^0.26.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0
  build_runner: ^1.10.0

flutter:
  uses-material-design: true
  assets:
    - images/
    - videos/
    - arrow.png

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Medium.ttf

